name: cdk

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  aws_cdk:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Main Branch Check
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "SYSTEM_ENV=stg" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Setup dependencies
        run: yarn ci

      - name: Build
        run: yarn run build

      - name: Unit tests
        if: contains(github.event_name, 'pull_request')
        run: yarn run test

      - name: CDK Diff Check
        if: contains(github.event_name, 'pull_request')
        run: yarn run cdk diff
        env:
          AWS_DEFAULT_REGION: "ap-northeast-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: CDK Deploy
        if: contains(github.event_name, 'push')
        run: yarn run deploy
        env:
          AWS_DEFAULT_REGION: "ap-northeast-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
